version: '3.8'
services:
  app:
    build: .
    container_name: atiato-app
    environment:
      - SQL_SERVER=sqlserver
      - SQL_DATABASE=atiato
      - SQL_USER=sa
      - SQL_PASSWORD=YourStrong!Passw0rd
      - KEY_VAULT_URL=http://keyvault
      - LOGIC_APP_URL=http://logicapp
    ports:
      - "8000:8000"
    depends_on:
      - sqlserver
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: atiato-sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
